import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout, { siteTitle } from "../components/layout";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import utilStyles from "../styles/utils.module.css";
import Date from '../components/date'

const Home = ({ allPostsData }: any) => {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>
          Hello there! I am Felipe Ramírez, and I love working with JavaScript
          related technologies.
        </p>
        <p>
          (This is a sample website - you’ll be building a site like this on{" "}
          <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
        </p>
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }: IBlogInfo) => (
            <li className={utilStyles.listItem} key={id}>
              <p>
                <Link href={`/posts/${id}`}>
                  <a>{title}</a>
                </Link>
              </p>
              <p>
                <small className={utilStyles.lighText}>
                  <Date dateString={date}/>  
                </small>
              </p>
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  );
};

export default Home;

import { getSortedPostsData } from "../lib/posts";
import { IBlogInfo } from "../lib/interface";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
